---
product-name: p-healthwatch2
network-properties:
  network:
    name: pas
  service_network:
    name: services
  other_availability_zones:
  - name: ((availability_zones.0))
  - name: ((availability_zones.1))
  - name: ((availability_zones.2))
  singleton_availability_zone:
    name: ((availability_zones.0))
product-properties:
  .properties.enable_basic_auth:
    selected_option: enabled
    value: enabled
  .properties.grafana_route:
    selected_option: tas
    value: tas
